language: node_js
deploy:
  provider: heroku
  api_key:
    secure: 42be40d2-b259-45bc-b155-3bd4231b20da
    app: PokerFriends
    on:
      repo: PokerFriends-INFRES-12/PokerFriends
      branch: recette
notifications:
  slack: pokerfriends-infres12:puvfRAB8FSqkym6tBMyc2IVY
